-- DROP USER LJSA CASCADE; 

-- DROP TABLESPACE LJSA_DATA INCLUDING CONTENTS AND DATAFILES;
-- DROP TABLESPACE LJSA_TEMP INCLUDING CONTENTS AND DATAFILES;

-- SELECT * FROM v$version;

CREATE TABLESPACE LJSA_DATA DATAFILE '/u02/app/oracle/oradata/ORCL/LJSA_DATA.dbf' SIZE 20M REUSE AUTOEXTEND ON NEXT 512K MAXSIZE 8192M;
CREATE TEMPORARY TABLESPACE LJSA_TEMP TEMPFILE '/u02/app/oracle/oradata/ORCL/LJSA_TEMP.dbf' SIZE 5M AUTOEXTEND ON;

-- SELECT * FROM V$DATAFILE
-- alter system set DEFERRED_SEGMENT_CREATION=FALSE scope=both; // To include empty tables in export

-- To create user LJSA without prefix C## in Oracle 12:
ALTER SESSION SET "_ORACLE_SCRIPT"=true;

-- USER SQL
CREATE USER LJSA IDENTIFIED BY PASS123 DEFAULT TABLESPACE "LJSA_DATA" TEMPORARY TABLESPACE "LJSA_TEMP";
-- ROLE
GRANT "RESOURCE" TO LJSA WITH ADMIN OPTION;
GRANT "CONNECT" TO LJSA WITH ADMIN OPTION;
ALTER USER LJSA DEFAULT ROLE "RESOURCE","CONNECT";
-- SYSTEM PRIVILEGES
GRANT CREATE SESSION TO LJSA WITH ADMIN OPTION;
GRANT CREATE TABLE TO LJSA WITH ADMIN OPTION;
GRANT CREATE PROCEDURE TO LJSA WITH ADMIN OPTION;
GRANT CREATE SEQUENCE TO LJSA WITH ADMIN OPTION;
GRANT CREATE ANY TRIGGER TO LJSA WITH ADMIN OPTION;
GRANT DROP ANY TRIGGER TO LJSA WITH ADMIN OPTION;
GRANT CREATE ANY INDEX TO LJSA WITH ADMIN OPTION;
GRANT DROP ANY INDEX TO LJSA WITH ADMIN OPTION;
GRANT CREATE ANY VIEW TO LJSA WITH ADMIN OPTION;
GRANT DROP ANY VIEW TO LJSA WITH ADMIN OPTION;

-- To prevent ora-01950 in Oracle 12:
GRANT UNLIMITED TABLESPACE TO LJSA;

-- PURGE RECYCLEBIN;
