--
-- Drop tables
--

DROP TABLE LJSA_LOG_FILES               CASCADE CONSTRAINTS PURGE;
DROP TABLE LJSA_LOG                     CASCADE CONSTRAINTS PURGE;

DROP TABLE LJSA_SCHEDULAZIONI_NOTIFICA  CASCADE CONSTRAINTS PURGE;
DROP TABLE LJSA_SCHEDULAZIONI_PARAMETRI CASCADE CONSTRAINTS PURGE;
DROP TABLE LJSA_SCHEDULAZIONI_CONF      CASCADE CONSTRAINTS PURGE;
DROP TABLE LJSA_SCHEDULAZIONI           CASCADE CONSTRAINTS PURGE;

DROP TABLE LJSA_ATTIVITA_NOTIFICA       CASCADE CONSTRAINTS PURGE;
DROP TABLE LJSA_ATTIVITA_PARAMETRI      CASCADE CONSTRAINTS PURGE;
DROP TABLE LJSA_ATTIVITA_CONF           CASCADE CONSTRAINTS PURGE;
DROP TABLE LJSA_ATTIVITA                CASCADE CONSTRAINTS PURGE;

DROP TABLE LJSA_CLASSI                  CASCADE CONSTRAINTS PURGE;

DROP TABLE LJSA_LOG_SCHEDULATORE        CASCADE CONSTRAINTS PURGE;
DROP TABLE LJSA_SCHEDULATORI            CASCADE CONSTRAINTS PURGE;
DROP TABLE LJSA_CREDENZIALI             CASCADE CONSTRAINTS PURGE;
DROP TABLE LJSA_SERVIZI                 CASCADE CONSTRAINTS PURGE;

-- Drop sequences

DROP SEQUENCE LJSA_SEQ_SCHEDULAZIONI;
DROP SEQUENCE LJSA_SEQ_LOG;
