--
-- Tables
--

CREATE TABLE LJSA_SERVIZI (
  ID_SERVIZIO         VARCHAR2(50)    NOT NULL,
  DESCRIZIONE         VARCHAR2(100)   NOT NULL,
  ATTIVO              VARCHAR2(1)     NOT NULL,
  CONSTRAINT PK_LJSA_SERVIZI PRIMARY KEY (ID_SERVIZIO));

CREATE TABLE LJSA_CREDENZIALI (
  ID_SERVIZIO         VARCHAR2(50)    NOT NULL,
  ID_CREDENZIALE      VARCHAR2(50)    NOT NULL,
  CREDENZIALI         VARCHAR2(100)   NOT NULL,
  EMAIL               VARCHAR2(100),
  ATTIVO              VARCHAR2(1)     NOT NULL,
  CONSTRAINT PK_LJSA_CREDENZIALI PRIMARY KEY (ID_SERVIZIO, ID_CREDENZIALE),
  CONSTRAINT FK_LJSA_CRED_ID_SER FOREIGN KEY (ID_SERVIZIO) REFERENCES LJSA_SERVIZI(ID_SERVIZIO));

CREATE TABLE LJSA_SCHEDULATORI (
  ID_SCHEDULATORE     VARCHAR2(50)    NOT NULL,
  URL_SERVIZIO        VARCHAR2(255)   NOT NULL,
  ATTIVO              VARCHAR2(1)     NOT NULL,
  CONSTRAINT PK_LJSA_SCHEDULATORI PRIMARY KEY (ID_SCHEDULATORE) );

CREATE TABLE LJSA_LOG_SCHEDULATORE (
  ID_SCHEDULATORE     VARCHAR2(50)    NOT NULL,
  DATA_SCHEDULAZIONE  NUMBER(8)       NOT NULL,
  ORA_SCHEDULAZIONE   NUMBER(4)       NOT NULL,
  DATA_AGGIORNAMENTO  NUMBER(8)       NOT NULL,
  ORA_AGGIORNAMENTO   NUMBER(4)       NOT NULL,
  CONSTRAINT PK_LJSA_LOG_SCHEDULATORE PRIMARY KEY (ID_SCHEDULATORE, DATA_SCHEDULAZIONE, ORA_SCHEDULAZIONE),
  CONSTRAINT FK_LJSA_LOG_SCHED_ID_SCH FOREIGN KEY (ID_SCHEDULATORE) REFERENCES LJSA_SCHEDULATORI(ID_SCHEDULATORE));

CREATE TABLE LJSA_CLASSI (
  CLASSE              VARCHAR2(255)   NOT NULL,
  DESCRIZIONE         VARCHAR2(255)   NOT NULL,
  CONSTRAINT PK_LJSA_CLASSI PRIMARY KEY (CLASSE));

CREATE TABLE LJSA_ATTIVITA (
  ID_SERVIZIO         VARCHAR2(50)    NOT NULL,
  ID_ATTIVITA         VARCHAR2(50)    NOT NULL,
  DESCRIZIONE         VARCHAR2(255)   NOT NULL,
  CLASSE              VARCHAR2(255)   NOT NULL,
  ATTIVO              VARCHAR2(1)     NOT NULL,
  ID_CREDENZIALE_INS  VARCHAR2(50)    NOT NULL,
  DATA_INSERIMENTO    NUMBER(8)       NOT NULL,
  ORA_INSERIMENTO     NUMBER(4)       NOT NULL,
  ID_CREDENZIALE_AGG  VARCHAR2(50)    NOT NULL,
  DATA_AGGIORNAMENTO  NUMBER(8)       NOT NULL,
  ORA_AGGIORNAMENTO   NUMBER(4)       NOT NULL,
  CONSTRAINT PK_LJSA_ATTIVITA PRIMARY KEY (ID_SERVIZIO, ID_ATTIVITA),
  CONSTRAINT FK_LJSA_LOG_ATT_CLASSE FOREIGN KEY (CLASSE) REFERENCES LJSA_CLASSI (CLASSE),
  CONSTRAINT FK_LJSA_LOG_ATT_ID_SER FOREIGN KEY (ID_SERVIZIO) REFERENCES LJSA_SERVIZI (ID_SERVIZIO),
  CONSTRAINT FK_LJSA_LOG_ATT_CR_INS FOREIGN KEY (ID_SERVIZIO, ID_CREDENZIALE_INS) REFERENCES LJSA_CREDENZIALI (ID_SERVIZIO, ID_CREDENZIALE), 
  CONSTRAINT FK_LJSA_LOG_ATT_CR_AGG FOREIGN KEY (ID_SERVIZIO, ID_CREDENZIALE_AGG) REFERENCES LJSA_CREDENZIALI (ID_SERVIZIO, ID_CREDENZIALE));

CREATE TABLE LJSA_ATTIVITA_CONF (
  ID_SERVIZIO         VARCHAR2(50)    NOT NULL,
  ID_ATTIVITA         VARCHAR2(50)    NOT NULL,
  OPZIONE             VARCHAR2(255)   NOT NULL,
  DESCRIZIONE         VARCHAR2(255)   NOT NULL,
  VALORI              VARCHAR2(255),
  PREDEFINITO         VARCHAR2(1024),
  CONSTRAINT PK_LJSA_ATTIVITA_CONF PRIMARY KEY (ID_SERVIZIO, ID_ATTIVITA, OPZIONE),
  CONSTRAINT FK_LJSA_ATT_CON_ID_ATT FOREIGN KEY (ID_SERVIZIO, ID_ATTIVITA) REFERENCES LJSA_ATTIVITA (ID_SERVIZIO, ID_ATTIVITA));

CREATE TABLE LJSA_ATTIVITA_PARAMETRI (
  ID_SERVIZIO  VARCHAR2(50)           NOT NULL,
  ID_ATTIVITA  VARCHAR2(50)           NOT NULL,
  PARAMETRO    VARCHAR2(255)          NOT NULL,
  DESCRIZIONE  VARCHAR2(255)          NOT NULL,
  VALORI       VARCHAR2(255),
  PREDEFINITO  VARCHAR2(1024),
  CONSTRAINT PK_LJSA_ATTIVITA_PARAMETRI PRIMARY KEY (ID_SERVIZIO, ID_ATTIVITA, PARAMETRO),
  CONSTRAINT FK_LJSA_ATT_PAR_ID_ATT FOREIGN KEY (ID_SERVIZIO, ID_ATTIVITA) REFERENCES LJSA_ATTIVITA (ID_SERVIZIO, ID_ATTIVITA));

CREATE TABLE LJSA_ATTIVITA_NOTIFICA (
  ID_SERVIZIO   VARCHAR2(50)          NOT NULL,
  ID_ATTIVITA   VARCHAR2(50)          NOT NULL,
  EVENTO        VARCHAR2(1)           NOT NULL,
  DESTINAZIONE  VARCHAR2(255)         NOT NULL,
  CONSTRAINT PK_LJSA_ATTIVITA_NOTIFICA PRIMARY KEY (ID_SERVIZIO, ID_ATTIVITA, EVENTO, DESTINAZIONE),
  CONSTRAINT FK_LJSA_ATT_NOT_ID_ATT FOREIGN KEY (ID_SERVIZIO, ID_ATTIVITA) REFERENCES LJSA_ATTIVITA (ID_SERVIZIO, ID_ATTIVITA));

CREATE TABLE LJSA_SCHEDULAZIONI (
  ID_SCHEDULAZIONE      NUMBER(10)    NOT NULL,
  ID_SERVIZIO           VARCHAR2(50)  NOT NULL,
  ID_ATTIVITA           VARCHAR2(50)  NOT NULL,
  DESCRIZIONE           VARCHAR2(255) NOT NULL,
  SCHEDULAZIONE         VARCHAR2(50)  NOT NULL,
  ID_CREDENZIALE_INS    VARCHAR2(50)  NOT NULL,
  DATA_INSERIMENTO      NUMBER(8)     NOT NULL,
  ORA_INSERIMENTO       NUMBER(4)     NOT NULL,
  ID_CREDENZIALE_AGG    VARCHAR2(50)  NOT NULL,
  DATA_AGGIORNAMENTO    NUMBER(8)     NOT NULL,
  ORA_AGGIORNAMENTO     NUMBER(4)     NOT NULL,
  STATO                 VARCHAR2(1)   NOT NULL,
  INIZIOVALIDITA        NUMBER(8)     NOT NULL,
  FINEVALIDITA          NUMBER(8)     NOT NULL,
  ESECUZIONI_COMPLETATE NUMBER(10)    NOT NULL,
  ESECUZIONI_INTERROTTE NUMBER(10)    NOT NULL,
  CONSTRAINT PK_LJSA_SCHEDULAZIONI PRIMARY KEY (ID_SCHEDULAZIONE),
  CONSTRAINT FK_LJSA_SCHED_ID_ATT FOREIGN KEY (ID_SERVIZIO, ID_ATTIVITA) REFERENCES LJSA_ATTIVITA (ID_SERVIZIO, ID_ATTIVITA),
  CONSTRAINT FK_LJSA_SCHED_CR_INS FOREIGN KEY (ID_SERVIZIO, ID_CREDENZIALE_INS) REFERENCES LJSA_CREDENZIALI (ID_SERVIZIO, ID_CREDENZIALE), 
  CONSTRAINT FK_LJSA_SCHED_CR_UPD FOREIGN KEY (ID_SERVIZIO, ID_CREDENZIALE_AGG) REFERENCES LJSA_CREDENZIALI (ID_SERVIZIO, ID_CREDENZIALE));

CREATE TABLE LJSA_SCHEDULAZIONI_CONF (
  ID_SCHEDULAZIONE NUMBER(10)         NOT NULL,
  OPZIONE          VARCHAR2(255)      NOT NULL,
  VALORE           VARCHAR2(1024),
  CONSTRAINT PK_LJSA_SCHEDULAZIONI_CONF PRIMARY KEY (ID_SCHEDULAZIONE, OPZIONE),
  CONSTRAINT FK_LJSA_SCH_CON_ID_SCH FOREIGN KEY (ID_SCHEDULAZIONE) REFERENCES LJSA_SCHEDULAZIONI (ID_SCHEDULAZIONE));

CREATE TABLE LJSA_SCHEDULAZIONI_PARAMETRI (
  ID_SCHEDULAZIONE NUMBER(10)         NOT NULL,
  PARAMETRO        VARCHAR2(255)      NOT NULL,
  VALORE           VARCHAR2(1024),
  CONSTRAINT PK_SCHEDULAZIONI_PARAMETRI PRIMARY KEY (ID_SCHEDULAZIONE, PARAMETRO),
  CONSTRAINT FK_LJSA_SCH_PAR_ID_SCH FOREIGN KEY (ID_SCHEDULAZIONE) REFERENCES LJSA_SCHEDULAZIONI (ID_SCHEDULAZIONE));

CREATE TABLE LJSA_SCHEDULAZIONI_NOTIFICA (
  ID_SCHEDULAZIONE NUMBER(10)         NOT NULL,
  EVENTO           VARCHAR2(1)        NOT NULL,
  DESTINAZIONE     VARCHAR2(255)      NOT NULL,
  CONSTRAINT PK_LJSA_SCHEDULAZIONI_NOTIFICA PRIMARY KEY (ID_SCHEDULAZIONE, EVENTO, DESTINAZIONE),
  CONSTRAINT FK_LJSA_SCH_NOT_ID_SCH FOREIGN KEY (ID_SCHEDULAZIONE) REFERENCES LJSA_SCHEDULAZIONI (ID_SCHEDULAZIONE));

CREATE TABLE LJSA_LOG (
  ID_LOG           NUMBER(10)         NOT NULL,
  ID_SCHEDULAZIONE NUMBER(10)         NOT NULL,
  DATA_INIZIO      NUMBER(8)          NOT NULL,
  ORA_INIZIO       NUMBER(4)          NOT NULL,
  DATA_FINE        NUMBER(8),
  ORA_FINE         NUMBER(4),
  RAPPORTO         VARCHAR2(255),
  STATO            VARCHAR2(1)        NOT NULL,
  CONSTRAINT PK_LJSA_LOG PRIMARY KEY (ID_LOG),
  CONSTRAINT FK_LJSA_LOG_ID_SCH FOREIGN KEY (ID_SCHEDULAZIONE) REFERENCES LJSA_SCHEDULAZIONI (ID_SCHEDULAZIONE));

CREATE TABLE LJSA_LOG_FILES (
  ID_LOG           NUMBER(10)         NOT NULL,
  NOME_FILE        VARCHAR2(255)      NOT NULL,
  TIPOLOGIA        VARCHAR2(1)        NOT NULL,
  URL_FILE         VARCHAR2(255)      NOT NULL,
  CONSTRAINT PK_LJSA_LOG_FILES PRIMARY KEY (ID_LOG, NOME_FILE),
  CONSTRAINT FK_LJSA_LOG_FILES_ID_LOG FOREIGN KEY (ID_LOG) REFERENCES LJSA_LOG (ID_LOG));
  
-- Indexes

CREATE INDEX IDX_LJSA_CRED_ID_CRED   ON LJSA_CREDENZIALI(ID_CREDENZIALE);
CREATE INDEX IDX_LJSA_CRED_EMAIL     ON LJSA_CREDENZIALI(EMAIL);

CREATE INDEX IDX_LJSA_SCHED_VALIDITA ON LJSA_SCHEDULAZIONI(INIZIOVALIDITA, FINEVALIDITA);

-- Sequences

CREATE SEQUENCE LJSA_SEQ_SCHEDULAZIONI START WITH 1 MAXVALUE 999999999999 MINVALUE 0 NOCYCLE NOCACHE NOORDER;
CREATE SEQUENCE LJSA_SEQ_LOG           START WITH 1 MAXVALUE 999999999999 MINVALUE 0 NOCYCLE NOCACHE NOORDER;
