--
-- Tables
--

CREATE TABLE LJSA_SERVIZI (
  ID_SERVIZIO         VARCHAR(50)    NOT NULL,
  DESCRIZIONE         VARCHAR(100)   NOT NULL,
  ATTIVO              VARCHAR(1)     NOT NULL,
  CONSTRAINT PK_LJSA_SERVIZI PRIMARY KEY (ID_SERVIZIO));

CREATE TABLE LJSA_CREDENZIALI (
  ID_SERVIZIO         VARCHAR(50)    NOT NULL,
  ID_CREDENZIALE      VARCHAR(50)    NOT NULL,
  CREDENZIALI         VARCHAR(100)   NOT NULL,
  EMAIL               VARCHAR(100),
  ATTIVO              VARCHAR(1)     NOT NULL,
  CONSTRAINT PK_LJSA_CREDENZIALI PRIMARY KEY (ID_SERVIZIO, ID_CREDENZIALE),
  CONSTRAINT FK_LJSA_CRED_ID_SER FOREIGN KEY (ID_SERVIZIO) REFERENCES LJSA_SERVIZI(ID_SERVIZIO));

CREATE TABLE LJSA_SCHEDULATORI (
  ID_SCHEDULATORE     VARCHAR(50)    NOT NULL,
  URL_SERVIZIO        VARCHAR(255)   NOT NULL,
  ATTIVO              VARCHAR(1)     NOT NULL,
  CONSTRAINT PK_LJSA_SCHEDULATORI PRIMARY KEY (ID_SCHEDULATORE) );

CREATE TABLE LJSA_LOG_SCHEDULATORE (
  ID_SCHEDULATORE     VARCHAR(50)    NOT NULL,
  DATA_SCHEDULAZIONE  INT            NOT NULL,
  ORA_SCHEDULAZIONE   INT            NOT NULL,
  DATA_AGGIORNAMENTO  INT            NOT NULL,
  ORA_AGGIORNAMENTO   INT            NOT NULL,
  CONSTRAINT PK_LJSA_LOG_SCHEDULATORE PRIMARY KEY (ID_SCHEDULATORE, DATA_SCHEDULAZIONE, ORA_SCHEDULAZIONE),
  CONSTRAINT FK_LJSA_LOG_SCHED_ID_SCH FOREIGN KEY (ID_SCHEDULATORE) REFERENCES LJSA_SCHEDULATORI(ID_SCHEDULATORE));

CREATE TABLE LJSA_CLASSI (
  CLASSE              VARCHAR(255)   NOT NULL,
  DESCRIZIONE         VARCHAR(255)   NOT NULL,
  CONSTRAINT PK_LJSA_CLASSI PRIMARY KEY (CLASSE));

CREATE TABLE LJSA_ATTIVITA (
  ID_SERVIZIO         VARCHAR(50)    NOT NULL,
  ID_ATTIVITA         VARCHAR(50)    NOT NULL,
  DESCRIZIONE         VARCHAR(255)   NOT NULL,
  CLASSE              VARCHAR(255)   NOT NULL,
  ATTIVO              VARCHAR(1)     NOT NULL,
  ID_CREDENZIALE_INS  VARCHAR(50)    NOT NULL,
  DATA_INSERIMENTO    INT            NOT NULL,
  ORA_INSERIMENTO     INT            NOT NULL,
  ID_CREDENZIALE_AGG  VARCHAR(50)    NOT NULL,
  DATA_AGGIORNAMENTO  INT            NOT NULL,
  ORA_AGGIORNAMENTO   INT            NOT NULL,
  CONSTRAINT PK_LJSA_ATTIVITA PRIMARY KEY (ID_SERVIZIO, ID_ATTIVITA),
  CONSTRAINT FK_LJSA_LOG_ATT_CLASSE FOREIGN KEY (CLASSE) REFERENCES LJSA_CLASSI (CLASSE),
  CONSTRAINT FK_LJSA_LOG_ATT_ID_SER FOREIGN KEY (ID_SERVIZIO) REFERENCES LJSA_SERVIZI (ID_SERVIZIO),
  CONSTRAINT FK_LJSA_LOG_ATT_CR_INS FOREIGN KEY (ID_SERVIZIO, ID_CREDENZIALE_INS) REFERENCES LJSA_CREDENZIALI (ID_SERVIZIO, ID_CREDENZIALE), 
  CONSTRAINT FK_LJSA_LOG_ATT_CR_AGG FOREIGN KEY (ID_SERVIZIO, ID_CREDENZIALE_AGG) REFERENCES LJSA_CREDENZIALI (ID_SERVIZIO, ID_CREDENZIALE));

CREATE TABLE LJSA_ATTIVITA_CONF (
  ID_SERVIZIO           VARCHAR(50)  NOT NULL,
  ID_ATTIVITA           VARCHAR(50)  NOT NULL,
  OPZIONE               VARCHAR(255) NOT NULL,
  DESCRIZIONE           VARCHAR(255) NOT NULL,
  VALORI                VARCHAR(255),
  PREDEFINITO           VARCHAR(255),
  CONSTRAINT PK_LJSA_ATTIVITA_CONF PRIMARY KEY (ID_SERVIZIO, ID_ATTIVITA, OPZIONE),
  CONSTRAINT FK_LJSA_ATT_CON_ID_ATT FOREIGN KEY (ID_SERVIZIO, ID_ATTIVITA) REFERENCES LJSA_ATTIVITA (ID_SERVIZIO, ID_ATTIVITA));

CREATE TABLE LJSA_ATTIVITA_PARAMETRI (
  ID_SERVIZIO           VARCHAR(50)  NOT NULL,
  ID_ATTIVITA           VARCHAR(50)  NOT NULL,
  PARAMETRO             VARCHAR(255) NOT NULL,
  DESCRIZIONE           VARCHAR(255) NOT NULL,
  VALORI                VARCHAR(255),
  PREDEFINITO           VARCHAR(255),
  CONSTRAINT PK_LJSA_ATTIVITA_PARAMETRI PRIMARY KEY (ID_SERVIZIO, ID_ATTIVITA, PARAMETRO),
  CONSTRAINT FK_LJSA_ATT_PAR_ID_ATT FOREIGN KEY (ID_SERVIZIO, ID_ATTIVITA) REFERENCES LJSA_ATTIVITA (ID_SERVIZIO, ID_ATTIVITA));

CREATE TABLE LJSA_ATTIVITA_NOTIFICA (
  ID_SERVIZIO           VARCHAR(50)  NOT NULL,
  ID_ATTIVITA           VARCHAR(50)  NOT NULL,
  EVENTO                VARCHAR(1)   NOT NULL,
  DESTINAZIONE          VARCHAR(255) NOT NULL,
  CONSTRAINT PK_LJSA_ATTIVITA_NOTIFICA PRIMARY KEY (ID_SERVIZIO, ID_ATTIVITA, EVENTO, DESTINAZIONE),
  CONSTRAINT FK_LJSA_ATT_NOT_ID_ATT FOREIGN KEY (ID_SERVIZIO, ID_ATTIVITA) REFERENCES LJSA_ATTIVITA (ID_SERVIZIO, ID_ATTIVITA));

CREATE TABLE LJSA_SCHEDULAZIONI (
  ID_SCHEDULAZIONE      INT          NOT NULL,
  ID_SERVIZIO           VARCHAR(50)  NOT NULL,
  ID_ATTIVITA           VARCHAR(50)  NOT NULL,
  DESCRIZIONE           VARCHAR(255) NOT NULL,
  SCHEDULAZIONE         VARCHAR(50)  NOT NULL,
  ID_CREDENZIALE_INS    VARCHAR(50)  NOT NULL,
  DATA_INSERIMENTO      INT          NOT NULL,
  ORA_INSERIMENTO       INT          NOT NULL,
  ID_CREDENZIALE_AGG    VARCHAR(50)  NOT NULL,
  DATA_AGGIORNAMENTO    INT          NOT NULL,
  ORA_AGGIORNAMENTO     INT          NOT NULL,
  STATO                 VARCHAR(1)   NOT NULL,
  INIZIOVALIDITA        INT          NOT NULL,
  FINEVALIDITA          INT          NOT NULL,
  ESECUZIONI_COMPLETATE INT          NOT NULL,
  ESECUZIONI_INTERROTTE INT          NOT NULL,
  CONSTRAINT PK_LJSA_SCHEDULAZIONI PRIMARY KEY (ID_SCHEDULAZIONE),
  CONSTRAINT FK_LJSA_SCHED_ID_ATT FOREIGN KEY (ID_SERVIZIO, ID_ATTIVITA) REFERENCES LJSA_ATTIVITA (ID_SERVIZIO, ID_ATTIVITA),
  CONSTRAINT FK_LJSA_SCHED_CR_INS FOREIGN KEY (ID_SERVIZIO, ID_CREDENZIALE_INS) REFERENCES LJSA_CREDENZIALI (ID_SERVIZIO, ID_CREDENZIALE), 
  CONSTRAINT FK_LJSA_SCHED_CR_UPD FOREIGN KEY (ID_SERVIZIO, ID_CREDENZIALE_AGG) REFERENCES LJSA_CREDENZIALI (ID_SERVIZIO, ID_CREDENZIALE));

CREATE TABLE LJSA_SCHEDULAZIONI_CONF (
  ID_SCHEDULAZIONE      INT          NOT NULL,
  OPZIONE               VARCHAR(255) NOT NULL,
  VALORE                VARCHAR(255),
  CONSTRAINT PK_LJSA_SCHEDULAZIONI_CONF PRIMARY KEY (ID_SCHEDULAZIONE, OPZIONE),
  CONSTRAINT FK_LJSA_SCH_CON_ID_SCH FOREIGN KEY (ID_SCHEDULAZIONE) REFERENCES LJSA_SCHEDULAZIONI (ID_SCHEDULAZIONE));

CREATE TABLE LJSA_SCHEDULAZIONI_PARAMETRI (
  ID_SCHEDULAZIONE      INT          NOT NULL,
  PARAMETRO             VARCHAR(255) NOT NULL,
  VALORE                VARCHAR(255),
  CONSTRAINT PK_SCHEDULAZIONI_PARAMETRI PRIMARY KEY (ID_SCHEDULAZIONE, PARAMETRO),
  CONSTRAINT FK_LJSA_SCH_PAR_ID_SCH FOREIGN KEY (ID_SCHEDULAZIONE) REFERENCES LJSA_SCHEDULAZIONI (ID_SCHEDULAZIONE));

CREATE TABLE LJSA_SCHEDULAZIONI_NOTIFICA (
  ID_SCHEDULAZIONE      INT          NOT NULL,
  EVENTO                VARCHAR(1)   NOT NULL,
  DESTINAZIONE          VARCHAR(255) NOT NULL,
  CONSTRAINT PK_LJSA_SCHEDULAZIONI_NOTIFICA PRIMARY KEY (ID_SCHEDULAZIONE, EVENTO, DESTINAZIONE),
  CONSTRAINT FK_LJSA_SCH_NOT_ID_SCH FOREIGN KEY (ID_SCHEDULAZIONE) REFERENCES LJSA_SCHEDULAZIONI (ID_SCHEDULAZIONE));

CREATE TABLE LJSA_LOG (
  ID_LOG                INT          NOT NULL,
  ID_SCHEDULAZIONE      INT          NOT NULL,
  DATA_INIZIO           INT          NOT NULL,
  ORA_INIZIO            INT          NOT NULL,
  DATA_FINE             INT,
  ORA_FINE              INT,
  RAPPORTO              VARCHAR(255),
  STATO                 VARCHAR(1)   NOT NULL,
  CONSTRAINT PK_LJSA_LOG PRIMARY KEY (ID_LOG),
  CONSTRAINT FK_LJSA_LOG_ID_SCH FOREIGN KEY (ID_SCHEDULAZIONE) REFERENCES LJSA_SCHEDULAZIONI (ID_SCHEDULAZIONE));

CREATE TABLE LJSA_LOG_FILES (
  ID_LOG                INT          NOT NULL,
  NOME_FILE             VARCHAR(255) NOT NULL,
  TIPOLOGIA             VARCHAR(1)   NOT NULL,
  URL_FILE              VARCHAR(255) NOT NULL,
  CONSTRAINT PK_LJSA_LOG_FILES PRIMARY KEY (ID_LOG, NOME_FILE),
  CONSTRAINT FK_LJSA_LOG_FILES_ID_LOG FOREIGN KEY (ID_LOG) REFERENCES LJSA_LOG (ID_LOG));
  
CREATE TABLE LJSA_PROGRESSIVI (
  CODICE                VARCHAR(50)  NOT NULL,
  VALORE                INT          NOT NULL,
  CONSTRAINT PK_LJSA_PROGRESSIVI PRIMARY KEY (CODICE));
  
-- Indexes

CREATE INDEX IDX_LJSA_CRED_ID_CRED   ON LJSA_CREDENZIALI(ID_CREDENZIALE);
CREATE INDEX IDX_LJSA_CRED_EMAIL     ON LJSA_CREDENZIALI(EMAIL);

CREATE INDEX IDX_LJSA_SCHED_VALIDITA ON LJSA_SCHEDULAZIONI(INIZIOVALIDITA, FINEVALIDITA);

