--
-- Data
--

INSERT INTO LJSA_SERVIZI(ID_SERVIZIO,DESCRIZIONE,ATTIVO) VALUES('LJSA','DEFAULT LJSA SERVICE','S');

-- admin / dew2006
INSERT INTO LJSA_CREDENZIALI(ID_SERVIZIO,ID_CREDENZIALE,CREDENZIALI,EMAIL,ATTIVO) VALUES('LJSA', 'admin', '1559035354', 'admin@dew.org', 'S');

INSERT INTO LJSA_CLASSI(CLASSE,DESCRIZIONE) VALUES('org.dew.ljsa.LJSQL',  'SQL command executor');
INSERT INTO LJSA_CLASSI(CLASSE,DESCRIZIONE) VALUES('org.dew.ljsa.LJTest', 'Test implementation');

COMMIT;